// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BlurtsColumns holds the columns for the "blurts" table.
	BlurtsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "content", Type: field.TypeString, Size: 14},
		{Name: "user_blurts", Type: field.TypeUUID, Nullable: true},
	}
	// BlurtsTable holds the schema information for the "blurts" table.
	BlurtsTable = &schema.Table{
		Name:       "blurts",
		Columns:    BlurtsColumns,
		PrimaryKey: []*schema.Column{BlurtsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "blurts_users_blurts",
				Columns:    []*schema.Column{BlurtsColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// LiksColumns holds the columns for the "liks" table.
	LiksColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "blurt_id", Type: field.TypeUUID},
	}
	// LiksTable holds the schema information for the "liks" table.
	LiksTable = &schema.Table{
		Name:       "liks",
		Columns:    LiksColumns,
		PrimaryKey: []*schema.Column{LiksColumns[0], LiksColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "liks_users_user",
				Columns:    []*schema.Column{LiksColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "liks_blurts_blurt",
				Columns:    []*schema.Column{LiksColumns[1]},
				RefColumns: []*schema.Column{BlurtsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "username", Type: field.TypeString, Unique: true, Size: 14},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BlurtsTable,
		LiksTable,
		UsersTable,
	}
)

func init() {
	BlurtsTable.ForeignKeys[0].RefTable = UsersTable
	LiksTable.ForeignKeys[0].RefTable = UsersTable
	LiksTable.ForeignKeys[1].RefTable = BlurtsTable
}
