// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Blurt is the predicate function for blurt builders.
type Blurt func(*sql.Selector)

// Lik is the predicate function for lik builders.
type Lik func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
