//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Blurt = newBlurtTable("", "blurt", "")

type blurtTable struct {
	sqlite.Table

	// Columns
	ID      sqlite.ColumnString
	Content sqlite.ColumnString
	Author  sqlite.ColumnString
	Created sqlite.ColumnString

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type BlurtTable struct {
	blurtTable

	EXCLUDED blurtTable
}

// AS creates new BlurtTable with assigned alias
func (a BlurtTable) AS(alias string) *BlurtTable {
	return newBlurtTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new BlurtTable with assigned schema name
func (a BlurtTable) FromSchema(schemaName string) *BlurtTable {
	return newBlurtTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new BlurtTable with assigned table prefix
func (a BlurtTable) WithPrefix(prefix string) *BlurtTable {
	return newBlurtTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new BlurtTable with assigned table suffix
func (a BlurtTable) WithSuffix(suffix string) *BlurtTable {
	return newBlurtTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newBlurtTable(schemaName, tableName, alias string) *BlurtTable {
	return &BlurtTable{
		blurtTable: newBlurtTableImpl(schemaName, tableName, alias),
		EXCLUDED:   newBlurtTableImpl("", "excluded", ""),
	}
}

func newBlurtTableImpl(schemaName, tableName, alias string) blurtTable {
	var (
		IDColumn       = sqlite.StringColumn("id")
		ContentColumn  = sqlite.StringColumn("content")
		AuthorColumn   = sqlite.StringColumn("author")
		CreatedColumn  = sqlite.StringColumn("created")
		allColumns     = sqlite.ColumnList{IDColumn, ContentColumn, AuthorColumn, CreatedColumn}
		mutableColumns = sqlite.ColumnList{ContentColumn, AuthorColumn, CreatedColumn}
		defaultColumns = sqlite.ColumnList{}
	)

	return blurtTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:      IDColumn,
		Content: ContentColumn,
		Author:  AuthorColumn,
		Created: CreatedColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
