// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/jeffreycharters/blurt/ent/blurt"
	"github.com/jeffreycharters/blurt/ent/user"
)

// BlurtCreate is the builder for creating a Blurt entity.
type BlurtCreate struct {
	config
	mutation *BlurtMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (bc *BlurtCreate) SetCreateTime(t time.Time) *BlurtCreate {
	bc.mutation.SetCreateTime(t)
	return bc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (bc *BlurtCreate) SetNillableCreateTime(t *time.Time) *BlurtCreate {
	if t != nil {
		bc.SetCreateTime(*t)
	}
	return bc
}

// SetUpdateTime sets the "update_time" field.
func (bc *BlurtCreate) SetUpdateTime(t time.Time) *BlurtCreate {
	bc.mutation.SetUpdateTime(t)
	return bc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (bc *BlurtCreate) SetNillableUpdateTime(t *time.Time) *BlurtCreate {
	if t != nil {
		bc.SetUpdateTime(*t)
	}
	return bc
}

// SetContent sets the "content" field.
func (bc *BlurtCreate) SetContent(s string) *BlurtCreate {
	bc.mutation.SetContent(s)
	return bc
}

// SetID sets the "id" field.
func (bc *BlurtCreate) SetID(u uuid.UUID) *BlurtCreate {
	bc.mutation.SetID(u)
	return bc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (bc *BlurtCreate) SetNillableID(u *uuid.UUID) *BlurtCreate {
	if u != nil {
		bc.SetID(*u)
	}
	return bc
}

// AddLikdUserIDs adds the "likd_users" edge to the User entity by IDs.
func (bc *BlurtCreate) AddLikdUserIDs(ids ...uuid.UUID) *BlurtCreate {
	bc.mutation.AddLikdUserIDs(ids...)
	return bc
}

// AddLikdUsers adds the "likd_users" edges to the User entity.
func (bc *BlurtCreate) AddLikdUsers(u ...*User) *BlurtCreate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return bc.AddLikdUserIDs(ids...)
}

// SetAuthorID sets the "author" edge to the User entity by ID.
func (bc *BlurtCreate) SetAuthorID(id uuid.UUID) *BlurtCreate {
	bc.mutation.SetAuthorID(id)
	return bc
}

// SetNillableAuthorID sets the "author" edge to the User entity by ID if the given value is not nil.
func (bc *BlurtCreate) SetNillableAuthorID(id *uuid.UUID) *BlurtCreate {
	if id != nil {
		bc = bc.SetAuthorID(*id)
	}
	return bc
}

// SetAuthor sets the "author" edge to the User entity.
func (bc *BlurtCreate) SetAuthor(u *User) *BlurtCreate {
	return bc.SetAuthorID(u.ID)
}

// Mutation returns the BlurtMutation object of the builder.
func (bc *BlurtCreate) Mutation() *BlurtMutation {
	return bc.mutation
}

// Save creates the Blurt in the database.
func (bc *BlurtCreate) Save(ctx context.Context) (*Blurt, error) {
	bc.defaults()
	return withHooks(ctx, bc.sqlSave, bc.mutation, bc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (bc *BlurtCreate) SaveX(ctx context.Context) *Blurt {
	v, err := bc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bc *BlurtCreate) Exec(ctx context.Context) error {
	_, err := bc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bc *BlurtCreate) ExecX(ctx context.Context) {
	if err := bc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bc *BlurtCreate) defaults() {
	if _, ok := bc.mutation.CreateTime(); !ok {
		v := blurt.DefaultCreateTime()
		bc.mutation.SetCreateTime(v)
	}
	if _, ok := bc.mutation.UpdateTime(); !ok {
		v := blurt.DefaultUpdateTime()
		bc.mutation.SetUpdateTime(v)
	}
	if _, ok := bc.mutation.ID(); !ok {
		v := blurt.DefaultID()
		bc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bc *BlurtCreate) check() error {
	if _, ok := bc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Blurt.create_time"`)}
	}
	if _, ok := bc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Blurt.update_time"`)}
	}
	if _, ok := bc.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Blurt.content"`)}
	}
	if v, ok := bc.mutation.Content(); ok {
		if err := blurt.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Blurt.content": %w`, err)}
		}
	}
	return nil
}

func (bc *BlurtCreate) sqlSave(ctx context.Context) (*Blurt, error) {
	if err := bc.check(); err != nil {
		return nil, err
	}
	_node, _spec := bc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	bc.mutation.id = &_node.ID
	bc.mutation.done = true
	return _node, nil
}

func (bc *BlurtCreate) createSpec() (*Blurt, *sqlgraph.CreateSpec) {
	var (
		_node = &Blurt{config: bc.config}
		_spec = sqlgraph.NewCreateSpec(blurt.Table, sqlgraph.NewFieldSpec(blurt.FieldID, field.TypeUUID))
	)
	if id, ok := bc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := bc.mutation.CreateTime(); ok {
		_spec.SetField(blurt.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := bc.mutation.UpdateTime(); ok {
		_spec.SetField(blurt.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := bc.mutation.Content(); ok {
		_spec.SetField(blurt.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if nodes := bc.mutation.LikdUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   blurt.LikdUsersTable,
			Columns: blurt.LikdUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := bc.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   blurt.AuthorTable,
			Columns: []string{blurt.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_blurts = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BlurtCreateBulk is the builder for creating many Blurt entities in bulk.
type BlurtCreateBulk struct {
	config
	err      error
	builders []*BlurtCreate
}

// Save creates the Blurt entities in the database.
func (bcb *BlurtCreateBulk) Save(ctx context.Context) ([]*Blurt, error) {
	if bcb.err != nil {
		return nil, bcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(bcb.builders))
	nodes := make([]*Blurt, len(bcb.builders))
	mutators := make([]Mutator, len(bcb.builders))
	for i := range bcb.builders {
		func(i int, root context.Context) {
			builder := bcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BlurtMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, bcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, bcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, bcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (bcb *BlurtCreateBulk) SaveX(ctx context.Context) []*Blurt {
	v, err := bcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bcb *BlurtCreateBulk) Exec(ctx context.Context) error {
	_, err := bcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bcb *BlurtCreateBulk) ExecX(ctx context.Context) {
	if err := bcb.Exec(ctx); err != nil {
		panic(err)
	}
}
