// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/jeffreycharters/blurt/ent/blurt"
	"github.com/jeffreycharters/blurt/ent/lik"
	"github.com/jeffreycharters/blurt/ent/predicate"
	"github.com/jeffreycharters/blurt/ent/user"
)

// BlurtQuery is the builder for querying Blurt entities.
type BlurtQuery struct {
	config
	ctx           *QueryContext
	order         []blurt.OrderOption
	inters        []Interceptor
	predicates    []predicate.Blurt
	withLikdUsers *UserQuery
	withAuthor    *UserQuery
	withLiks      *LikQuery
	withFKs       bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BlurtQuery builder.
func (bq *BlurtQuery) Where(ps ...predicate.Blurt) *BlurtQuery {
	bq.predicates = append(bq.predicates, ps...)
	return bq
}

// Limit the number of records to be returned by this query.
func (bq *BlurtQuery) Limit(limit int) *BlurtQuery {
	bq.ctx.Limit = &limit
	return bq
}

// Offset to start from.
func (bq *BlurtQuery) Offset(offset int) *BlurtQuery {
	bq.ctx.Offset = &offset
	return bq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (bq *BlurtQuery) Unique(unique bool) *BlurtQuery {
	bq.ctx.Unique = &unique
	return bq
}

// Order specifies how the records should be ordered.
func (bq *BlurtQuery) Order(o ...blurt.OrderOption) *BlurtQuery {
	bq.order = append(bq.order, o...)
	return bq
}

// QueryLikdUsers chains the current query on the "likd_users" edge.
func (bq *BlurtQuery) QueryLikdUsers() *UserQuery {
	query := (&UserClient{config: bq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(blurt.Table, blurt.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, blurt.LikdUsersTable, blurt.LikdUsersPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(bq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAuthor chains the current query on the "author" edge.
func (bq *BlurtQuery) QueryAuthor() *UserQuery {
	query := (&UserClient{config: bq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(blurt.Table, blurt.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, blurt.AuthorTable, blurt.AuthorColumn),
		)
		fromU = sqlgraph.SetNeighbors(bq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryLiks chains the current query on the "liks" edge.
func (bq *BlurtQuery) QueryLiks() *LikQuery {
	query := (&LikClient{config: bq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(blurt.Table, blurt.FieldID, selector),
			sqlgraph.To(lik.Table, lik.BlurtColumn),
			sqlgraph.Edge(sqlgraph.O2M, true, blurt.LiksTable, blurt.LiksColumn),
		)
		fromU = sqlgraph.SetNeighbors(bq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Blurt entity from the query.
// Returns a *NotFoundError when no Blurt was found.
func (bq *BlurtQuery) First(ctx context.Context) (*Blurt, error) {
	nodes, err := bq.Limit(1).All(setContextOp(ctx, bq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{blurt.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (bq *BlurtQuery) FirstX(ctx context.Context) *Blurt {
	node, err := bq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Blurt ID from the query.
// Returns a *NotFoundError when no Blurt ID was found.
func (bq *BlurtQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = bq.Limit(1).IDs(setContextOp(ctx, bq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{blurt.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (bq *BlurtQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := bq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Blurt entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Blurt entity is found.
// Returns a *NotFoundError when no Blurt entities are found.
func (bq *BlurtQuery) Only(ctx context.Context) (*Blurt, error) {
	nodes, err := bq.Limit(2).All(setContextOp(ctx, bq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{blurt.Label}
	default:
		return nil, &NotSingularError{blurt.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (bq *BlurtQuery) OnlyX(ctx context.Context) *Blurt {
	node, err := bq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Blurt ID in the query.
// Returns a *NotSingularError when more than one Blurt ID is found.
// Returns a *NotFoundError when no entities are found.
func (bq *BlurtQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = bq.Limit(2).IDs(setContextOp(ctx, bq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{blurt.Label}
	default:
		err = &NotSingularError{blurt.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (bq *BlurtQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := bq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Blurts.
func (bq *BlurtQuery) All(ctx context.Context) ([]*Blurt, error) {
	ctx = setContextOp(ctx, bq.ctx, "All")
	if err := bq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Blurt, *BlurtQuery]()
	return withInterceptors[[]*Blurt](ctx, bq, qr, bq.inters)
}

// AllX is like All, but panics if an error occurs.
func (bq *BlurtQuery) AllX(ctx context.Context) []*Blurt {
	nodes, err := bq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Blurt IDs.
func (bq *BlurtQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if bq.ctx.Unique == nil && bq.path != nil {
		bq.Unique(true)
	}
	ctx = setContextOp(ctx, bq.ctx, "IDs")
	if err = bq.Select(blurt.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (bq *BlurtQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := bq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (bq *BlurtQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, bq.ctx, "Count")
	if err := bq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, bq, querierCount[*BlurtQuery](), bq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (bq *BlurtQuery) CountX(ctx context.Context) int {
	count, err := bq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (bq *BlurtQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, bq.ctx, "Exist")
	switch _, err := bq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (bq *BlurtQuery) ExistX(ctx context.Context) bool {
	exist, err := bq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BlurtQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (bq *BlurtQuery) Clone() *BlurtQuery {
	if bq == nil {
		return nil
	}
	return &BlurtQuery{
		config:        bq.config,
		ctx:           bq.ctx.Clone(),
		order:         append([]blurt.OrderOption{}, bq.order...),
		inters:        append([]Interceptor{}, bq.inters...),
		predicates:    append([]predicate.Blurt{}, bq.predicates...),
		withLikdUsers: bq.withLikdUsers.Clone(),
		withAuthor:    bq.withAuthor.Clone(),
		withLiks:      bq.withLiks.Clone(),
		// clone intermediate query.
		sql:  bq.sql.Clone(),
		path: bq.path,
	}
}

// WithLikdUsers tells the query-builder to eager-load the nodes that are connected to
// the "likd_users" edge. The optional arguments are used to configure the query builder of the edge.
func (bq *BlurtQuery) WithLikdUsers(opts ...func(*UserQuery)) *BlurtQuery {
	query := (&UserClient{config: bq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bq.withLikdUsers = query
	return bq
}

// WithAuthor tells the query-builder to eager-load the nodes that are connected to
// the "author" edge. The optional arguments are used to configure the query builder of the edge.
func (bq *BlurtQuery) WithAuthor(opts ...func(*UserQuery)) *BlurtQuery {
	query := (&UserClient{config: bq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bq.withAuthor = query
	return bq
}

// WithLiks tells the query-builder to eager-load the nodes that are connected to
// the "liks" edge. The optional arguments are used to configure the query builder of the edge.
func (bq *BlurtQuery) WithLiks(opts ...func(*LikQuery)) *BlurtQuery {
	query := (&LikClient{config: bq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bq.withLiks = query
	return bq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Blurt.Query().
//		GroupBy(blurt.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (bq *BlurtQuery) GroupBy(field string, fields ...string) *BlurtGroupBy {
	bq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BlurtGroupBy{build: bq}
	grbuild.flds = &bq.ctx.Fields
	grbuild.label = blurt.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.Blurt.Query().
//		Select(blurt.FieldCreateTime).
//		Scan(ctx, &v)
func (bq *BlurtQuery) Select(fields ...string) *BlurtSelect {
	bq.ctx.Fields = append(bq.ctx.Fields, fields...)
	sbuild := &BlurtSelect{BlurtQuery: bq}
	sbuild.label = blurt.Label
	sbuild.flds, sbuild.scan = &bq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BlurtSelect configured with the given aggregations.
func (bq *BlurtQuery) Aggregate(fns ...AggregateFunc) *BlurtSelect {
	return bq.Select().Aggregate(fns...)
}

func (bq *BlurtQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range bq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, bq); err != nil {
				return err
			}
		}
	}
	for _, f := range bq.ctx.Fields {
		if !blurt.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if bq.path != nil {
		prev, err := bq.path(ctx)
		if err != nil {
			return err
		}
		bq.sql = prev
	}
	return nil
}

func (bq *BlurtQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Blurt, error) {
	var (
		nodes       = []*Blurt{}
		withFKs     = bq.withFKs
		_spec       = bq.querySpec()
		loadedTypes = [3]bool{
			bq.withLikdUsers != nil,
			bq.withAuthor != nil,
			bq.withLiks != nil,
		}
	)
	if bq.withAuthor != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, blurt.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Blurt).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Blurt{config: bq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, bq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := bq.withLikdUsers; query != nil {
		if err := bq.loadLikdUsers(ctx, query, nodes,
			func(n *Blurt) { n.Edges.LikdUsers = []*User{} },
			func(n *Blurt, e *User) { n.Edges.LikdUsers = append(n.Edges.LikdUsers, e) }); err != nil {
			return nil, err
		}
	}
	if query := bq.withAuthor; query != nil {
		if err := bq.loadAuthor(ctx, query, nodes, nil,
			func(n *Blurt, e *User) { n.Edges.Author = e }); err != nil {
			return nil, err
		}
	}
	if query := bq.withLiks; query != nil {
		if err := bq.loadLiks(ctx, query, nodes,
			func(n *Blurt) { n.Edges.Liks = []*Lik{} },
			func(n *Blurt, e *Lik) { n.Edges.Liks = append(n.Edges.Liks, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (bq *BlurtQuery) loadLikdUsers(ctx context.Context, query *UserQuery, nodes []*Blurt, init func(*Blurt), assign func(*Blurt, *User)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[uuid.UUID]*Blurt)
	nids := make(map[uuid.UUID]map[*Blurt]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(blurt.LikdUsersTable)
		s.Join(joinT).On(s.C(user.FieldID), joinT.C(blurt.LikdUsersPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(blurt.LikdUsersPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(blurt.LikdUsersPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(uuid.UUID)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := *values[0].(*uuid.UUID)
				inValue := *values[1].(*uuid.UUID)
				if nids[inValue] == nil {
					nids[inValue] = map[*Blurt]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*User](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "likd_users" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (bq *BlurtQuery) loadAuthor(ctx context.Context, query *UserQuery, nodes []*Blurt, init func(*Blurt), assign func(*Blurt, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Blurt)
	for i := range nodes {
		if nodes[i].user_blurts == nil {
			continue
		}
		fk := *nodes[i].user_blurts
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_blurts" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (bq *BlurtQuery) loadLiks(ctx context.Context, query *LikQuery, nodes []*Blurt, init func(*Blurt), assign func(*Blurt, *Lik)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Blurt)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(lik.FieldBlurtID)
	}
	query.Where(predicate.Lik(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(blurt.LiksColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.BlurtID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "blurt_id" returned %v for node %v`, fk, n)
		}
		assign(node, n)
	}
	return nil
}

func (bq *BlurtQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := bq.querySpec()
	_spec.Node.Columns = bq.ctx.Fields
	if len(bq.ctx.Fields) > 0 {
		_spec.Unique = bq.ctx.Unique != nil && *bq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, bq.driver, _spec)
}

func (bq *BlurtQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(blurt.Table, blurt.Columns, sqlgraph.NewFieldSpec(blurt.FieldID, field.TypeUUID))
	_spec.From = bq.sql
	if unique := bq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if bq.path != nil {
		_spec.Unique = true
	}
	if fields := bq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, blurt.FieldID)
		for i := range fields {
			if fields[i] != blurt.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := bq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := bq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := bq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := bq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (bq *BlurtQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(bq.driver.Dialect())
	t1 := builder.Table(blurt.Table)
	columns := bq.ctx.Fields
	if len(columns) == 0 {
		columns = blurt.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if bq.sql != nil {
		selector = bq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if bq.ctx.Unique != nil && *bq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range bq.predicates {
		p(selector)
	}
	for _, p := range bq.order {
		p(selector)
	}
	if offset := bq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := bq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BlurtGroupBy is the group-by builder for Blurt entities.
type BlurtGroupBy struct {
	selector
	build *BlurtQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (bgb *BlurtGroupBy) Aggregate(fns ...AggregateFunc) *BlurtGroupBy {
	bgb.fns = append(bgb.fns, fns...)
	return bgb
}

// Scan applies the selector query and scans the result into the given value.
func (bgb *BlurtGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bgb.build.ctx, "GroupBy")
	if err := bgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BlurtQuery, *BlurtGroupBy](ctx, bgb.build, bgb, bgb.build.inters, v)
}

func (bgb *BlurtGroupBy) sqlScan(ctx context.Context, root *BlurtQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(bgb.fns))
	for _, fn := range bgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*bgb.flds)+len(bgb.fns))
		for _, f := range *bgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*bgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BlurtSelect is the builder for selecting fields of Blurt entities.
type BlurtSelect struct {
	*BlurtQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (bs *BlurtSelect) Aggregate(fns ...AggregateFunc) *BlurtSelect {
	bs.fns = append(bs.fns, fns...)
	return bs
}

// Scan applies the selector query and scans the result into the given value.
func (bs *BlurtSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bs.ctx, "Select")
	if err := bs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BlurtQuery, *BlurtSelect](ctx, bs.BlurtQuery, bs, bs.inters, v)
}

func (bs *BlurtSelect) sqlScan(ctx context.Context, root *BlurtQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(bs.fns))
	for _, fn := range bs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*bs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
