// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/google/uuid"
	"github.com/jeffreycharters/blurt/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/jeffreycharters/blurt/ent/blurt"
	"github.com/jeffreycharters/blurt/ent/lik"
	"github.com/jeffreycharters/blurt/ent/user"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Blurt is the client for interacting with the Blurt builders.
	Blurt *BlurtClient
	// Lik is the client for interacting with the Lik builders.
	Lik *LikClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Blurt = NewBlurtClient(c.config)
	c.Lik = NewLikClient(c.config)
	c.User = NewUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Blurt:  NewBlurtClient(cfg),
		Lik:    NewLikClient(cfg),
		User:   NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Blurt:  NewBlurtClient(cfg),
		Lik:    NewLikClient(cfg),
		User:   NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Blurt.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Blurt.Use(hooks...)
	c.Lik.Use(hooks...)
	c.User.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Blurt.Intercept(interceptors...)
	c.Lik.Intercept(interceptors...)
	c.User.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *BlurtMutation:
		return c.Blurt.mutate(ctx, m)
	case *LikMutation:
		return c.Lik.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// BlurtClient is a client for the Blurt schema.
type BlurtClient struct {
	config
}

// NewBlurtClient returns a client for the Blurt from the given config.
func NewBlurtClient(c config) *BlurtClient {
	return &BlurtClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `blurt.Hooks(f(g(h())))`.
func (c *BlurtClient) Use(hooks ...Hook) {
	c.hooks.Blurt = append(c.hooks.Blurt, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `blurt.Intercept(f(g(h())))`.
func (c *BlurtClient) Intercept(interceptors ...Interceptor) {
	c.inters.Blurt = append(c.inters.Blurt, interceptors...)
}

// Create returns a builder for creating a Blurt entity.
func (c *BlurtClient) Create() *BlurtCreate {
	mutation := newBlurtMutation(c.config, OpCreate)
	return &BlurtCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Blurt entities.
func (c *BlurtClient) CreateBulk(builders ...*BlurtCreate) *BlurtCreateBulk {
	return &BlurtCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BlurtClient) MapCreateBulk(slice any, setFunc func(*BlurtCreate, int)) *BlurtCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BlurtCreateBulk{err: fmt.Errorf("calling to BlurtClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BlurtCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BlurtCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Blurt.
func (c *BlurtClient) Update() *BlurtUpdate {
	mutation := newBlurtMutation(c.config, OpUpdate)
	return &BlurtUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BlurtClient) UpdateOne(b *Blurt) *BlurtUpdateOne {
	mutation := newBlurtMutation(c.config, OpUpdateOne, withBlurt(b))
	return &BlurtUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BlurtClient) UpdateOneID(id uuid.UUID) *BlurtUpdateOne {
	mutation := newBlurtMutation(c.config, OpUpdateOne, withBlurtID(id))
	return &BlurtUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Blurt.
func (c *BlurtClient) Delete() *BlurtDelete {
	mutation := newBlurtMutation(c.config, OpDelete)
	return &BlurtDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BlurtClient) DeleteOne(b *Blurt) *BlurtDeleteOne {
	return c.DeleteOneID(b.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BlurtClient) DeleteOneID(id uuid.UUID) *BlurtDeleteOne {
	builder := c.Delete().Where(blurt.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BlurtDeleteOne{builder}
}

// Query returns a query builder for Blurt.
func (c *BlurtClient) Query() *BlurtQuery {
	return &BlurtQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBlurt},
		inters: c.Interceptors(),
	}
}

// Get returns a Blurt entity by its id.
func (c *BlurtClient) Get(ctx context.Context, id uuid.UUID) (*Blurt, error) {
	return c.Query().Where(blurt.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BlurtClient) GetX(ctx context.Context, id uuid.UUID) *Blurt {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryLikdUsers queries the likd_users edge of a Blurt.
func (c *BlurtClient) QueryLikdUsers(b *Blurt) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := b.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(blurt.Table, blurt.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, blurt.LikdUsersTable, blurt.LikdUsersPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(b.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryAuthor queries the author edge of a Blurt.
func (c *BlurtClient) QueryAuthor(b *Blurt) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := b.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(blurt.Table, blurt.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, blurt.AuthorTable, blurt.AuthorColumn),
		)
		fromV = sqlgraph.Neighbors(b.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryLiks queries the liks edge of a Blurt.
func (c *BlurtClient) QueryLiks(b *Blurt) *LikQuery {
	query := (&LikClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := b.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(blurt.Table, blurt.FieldID, id),
			sqlgraph.To(lik.Table, lik.BlurtColumn),
			sqlgraph.Edge(sqlgraph.O2M, true, blurt.LiksTable, blurt.LiksColumn),
		)
		fromV = sqlgraph.Neighbors(b.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *BlurtClient) Hooks() []Hook {
	return c.hooks.Blurt
}

// Interceptors returns the client interceptors.
func (c *BlurtClient) Interceptors() []Interceptor {
	return c.inters.Blurt
}

func (c *BlurtClient) mutate(ctx context.Context, m *BlurtMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BlurtCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BlurtUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BlurtUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BlurtDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Blurt mutation op: %q", m.Op())
	}
}

// LikClient is a client for the Lik schema.
type LikClient struct {
	config
}

// NewLikClient returns a client for the Lik from the given config.
func NewLikClient(c config) *LikClient {
	return &LikClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `lik.Hooks(f(g(h())))`.
func (c *LikClient) Use(hooks ...Hook) {
	c.hooks.Lik = append(c.hooks.Lik, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `lik.Intercept(f(g(h())))`.
func (c *LikClient) Intercept(interceptors ...Interceptor) {
	c.inters.Lik = append(c.inters.Lik, interceptors...)
}

// Create returns a builder for creating a Lik entity.
func (c *LikClient) Create() *LikCreate {
	mutation := newLikMutation(c.config, OpCreate)
	return &LikCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Lik entities.
func (c *LikClient) CreateBulk(builders ...*LikCreate) *LikCreateBulk {
	return &LikCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *LikClient) MapCreateBulk(slice any, setFunc func(*LikCreate, int)) *LikCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &LikCreateBulk{err: fmt.Errorf("calling to LikClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*LikCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &LikCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Lik.
func (c *LikClient) Update() *LikUpdate {
	mutation := newLikMutation(c.config, OpUpdate)
	return &LikUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *LikClient) UpdateOne(l *Lik) *LikUpdateOne {
	mutation := newLikMutation(c.config, OpUpdateOne)
	mutation.user = &l.UserID
	mutation.blurt = &l.BlurtID
	return &LikUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Lik.
func (c *LikClient) Delete() *LikDelete {
	mutation := newLikMutation(c.config, OpDelete)
	return &LikDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Query returns a query builder for Lik.
func (c *LikClient) Query() *LikQuery {
	return &LikQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeLik},
		inters: c.Interceptors(),
	}
}

// QueryUser queries the user edge of a Lik.
func (c *LikClient) QueryUser(l *Lik) *UserQuery {
	return c.Query().
		Where(lik.UserID(l.UserID), lik.BlurtID(l.BlurtID)).
		QueryUser()
}

// QueryBlurt queries the blurt edge of a Lik.
func (c *LikClient) QueryBlurt(l *Lik) *BlurtQuery {
	return c.Query().
		Where(lik.UserID(l.UserID), lik.BlurtID(l.BlurtID)).
		QueryBlurt()
}

// Hooks returns the client hooks.
func (c *LikClient) Hooks() []Hook {
	return c.hooks.Lik
}

// Interceptors returns the client interceptors.
func (c *LikClient) Interceptors() []Interceptor {
	return c.inters.Lik
}

func (c *LikClient) mutate(ctx context.Context, m *LikMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&LikCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&LikUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&LikUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&LikDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Lik mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(u *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(u))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id uuid.UUID) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(u *User) *UserDeleteOne {
	return c.DeleteOneID(u.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id uuid.UUID) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id uuid.UUID) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id uuid.UUID) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryBlurts queries the blurts edge of a User.
func (c *UserClient) QueryBlurts(u *User) *BlurtQuery {
	query := (&BlurtClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(blurt.Table, blurt.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.BlurtsTable, user.BlurtsColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryLikdBlurts queries the likd_blurts edge of a User.
func (c *UserClient) QueryLikdBlurts(u *User) *BlurtQuery {
	query := (&BlurtClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(blurt.Table, blurt.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, user.LikdBlurtsTable, user.LikdBlurtsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryLiks queries the liks edge of a User.
func (c *UserClient) QueryLiks(u *User) *LikQuery {
	query := (&LikClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(lik.Table, lik.UserColumn),
			sqlgraph.Edge(sqlgraph.O2M, true, user.LiksTable, user.LiksColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Blurt, Lik, User []ent.Hook
	}
	inters struct {
		Blurt, Lik, User []ent.Interceptor
	}
)
