// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/jeffreycharters/blurt/ent/blurt"
	"github.com/jeffreycharters/blurt/ent/lik"
	"github.com/jeffreycharters/blurt/ent/predicate"
	"github.com/jeffreycharters/blurt/ent/user"
)

// LikQuery is the builder for querying Lik entities.
type LikQuery struct {
	config
	ctx        *QueryContext
	order      []lik.OrderOption
	inters     []Interceptor
	predicates []predicate.Lik
	withUser   *UserQuery
	withBlurt  *BlurtQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LikQuery builder.
func (lq *LikQuery) Where(ps ...predicate.Lik) *LikQuery {
	lq.predicates = append(lq.predicates, ps...)
	return lq
}

// Limit the number of records to be returned by this query.
func (lq *LikQuery) Limit(limit int) *LikQuery {
	lq.ctx.Limit = &limit
	return lq
}

// Offset to start from.
func (lq *LikQuery) Offset(offset int) *LikQuery {
	lq.ctx.Offset = &offset
	return lq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (lq *LikQuery) Unique(unique bool) *LikQuery {
	lq.ctx.Unique = &unique
	return lq
}

// Order specifies how the records should be ordered.
func (lq *LikQuery) Order(o ...lik.OrderOption) *LikQuery {
	lq.order = append(lq.order, o...)
	return lq
}

// QueryUser chains the current query on the "user" edge.
func (lq *LikQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: lq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := lq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := lq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(lik.Table, lik.UserColumn, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, lik.UserTable, lik.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(lq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryBlurt chains the current query on the "blurt" edge.
func (lq *LikQuery) QueryBlurt() *BlurtQuery {
	query := (&BlurtClient{config: lq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := lq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := lq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(lik.Table, lik.BlurtColumn, selector),
			sqlgraph.To(blurt.Table, blurt.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, lik.BlurtTable, lik.BlurtColumn),
		)
		fromU = sqlgraph.SetNeighbors(lq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Lik entity from the query.
// Returns a *NotFoundError when no Lik was found.
func (lq *LikQuery) First(ctx context.Context) (*Lik, error) {
	nodes, err := lq.Limit(1).All(setContextOp(ctx, lq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{lik.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (lq *LikQuery) FirstX(ctx context.Context) *Lik {
	node, err := lq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// Only returns a single Lik entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Lik entity is found.
// Returns a *NotFoundError when no Lik entities are found.
func (lq *LikQuery) Only(ctx context.Context) (*Lik, error) {
	nodes, err := lq.Limit(2).All(setContextOp(ctx, lq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{lik.Label}
	default:
		return nil, &NotSingularError{lik.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (lq *LikQuery) OnlyX(ctx context.Context) *Lik {
	node, err := lq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// All executes the query and returns a list of Liks.
func (lq *LikQuery) All(ctx context.Context) ([]*Lik, error) {
	ctx = setContextOp(ctx, lq.ctx, "All")
	if err := lq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Lik, *LikQuery]()
	return withInterceptors[[]*Lik](ctx, lq, qr, lq.inters)
}

// AllX is like All, but panics if an error occurs.
func (lq *LikQuery) AllX(ctx context.Context) []*Lik {
	nodes, err := lq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// Count returns the count of the given query.
func (lq *LikQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, lq.ctx, "Count")
	if err := lq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, lq, querierCount[*LikQuery](), lq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (lq *LikQuery) CountX(ctx context.Context) int {
	count, err := lq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (lq *LikQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, lq.ctx, "Exist")
	switch _, err := lq.First(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (lq *LikQuery) ExistX(ctx context.Context) bool {
	exist, err := lq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LikQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (lq *LikQuery) Clone() *LikQuery {
	if lq == nil {
		return nil
	}
	return &LikQuery{
		config:     lq.config,
		ctx:        lq.ctx.Clone(),
		order:      append([]lik.OrderOption{}, lq.order...),
		inters:     append([]Interceptor{}, lq.inters...),
		predicates: append([]predicate.Lik{}, lq.predicates...),
		withUser:   lq.withUser.Clone(),
		withBlurt:  lq.withBlurt.Clone(),
		// clone intermediate query.
		sql:  lq.sql.Clone(),
		path: lq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (lq *LikQuery) WithUser(opts ...func(*UserQuery)) *LikQuery {
	query := (&UserClient{config: lq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	lq.withUser = query
	return lq
}

// WithBlurt tells the query-builder to eager-load the nodes that are connected to
// the "blurt" edge. The optional arguments are used to configure the query builder of the edge.
func (lq *LikQuery) WithBlurt(opts ...func(*BlurtQuery)) *LikQuery {
	query := (&BlurtClient{config: lq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	lq.withBlurt = query
	return lq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID uuid.UUID `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Lik.Query().
//		GroupBy(lik.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (lq *LikQuery) GroupBy(field string, fields ...string) *LikGroupBy {
	lq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LikGroupBy{build: lq}
	grbuild.flds = &lq.ctx.Fields
	grbuild.label = lik.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID uuid.UUID `json:"user_id,omitempty"`
//	}
//
//	client.Lik.Query().
//		Select(lik.FieldUserID).
//		Scan(ctx, &v)
func (lq *LikQuery) Select(fields ...string) *LikSelect {
	lq.ctx.Fields = append(lq.ctx.Fields, fields...)
	sbuild := &LikSelect{LikQuery: lq}
	sbuild.label = lik.Label
	sbuild.flds, sbuild.scan = &lq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LikSelect configured with the given aggregations.
func (lq *LikQuery) Aggregate(fns ...AggregateFunc) *LikSelect {
	return lq.Select().Aggregate(fns...)
}

func (lq *LikQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range lq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, lq); err != nil {
				return err
			}
		}
	}
	for _, f := range lq.ctx.Fields {
		if !lik.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if lq.path != nil {
		prev, err := lq.path(ctx)
		if err != nil {
			return err
		}
		lq.sql = prev
	}
	return nil
}

func (lq *LikQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Lik, error) {
	var (
		nodes       = []*Lik{}
		_spec       = lq.querySpec()
		loadedTypes = [2]bool{
			lq.withUser != nil,
			lq.withBlurt != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Lik).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Lik{config: lq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, lq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := lq.withUser; query != nil {
		if err := lq.loadUser(ctx, query, nodes, nil,
			func(n *Lik, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := lq.withBlurt; query != nil {
		if err := lq.loadBlurt(ctx, query, nodes, nil,
			func(n *Lik, e *Blurt) { n.Edges.Blurt = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (lq *LikQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*Lik, init func(*Lik), assign func(*Lik, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Lik)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (lq *LikQuery) loadBlurt(ctx context.Context, query *BlurtQuery, nodes []*Lik, init func(*Lik), assign func(*Lik, *Blurt)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Lik)
	for i := range nodes {
		fk := nodes[i].BlurtID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(blurt.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "blurt_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (lq *LikQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := lq.querySpec()
	_spec.Unique = false
	_spec.Node.Columns = nil
	return sqlgraph.CountNodes(ctx, lq.driver, _spec)
}

func (lq *LikQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(lik.Table, lik.Columns, nil)
	_spec.From = lq.sql
	if unique := lq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if lq.path != nil {
		_spec.Unique = true
	}
	if fields := lq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		for i := range fields {
			_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
		}
		if lq.withUser != nil {
			_spec.Node.AddColumnOnce(lik.FieldUserID)
		}
		if lq.withBlurt != nil {
			_spec.Node.AddColumnOnce(lik.FieldBlurtID)
		}
	}
	if ps := lq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := lq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := lq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := lq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (lq *LikQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(lq.driver.Dialect())
	t1 := builder.Table(lik.Table)
	columns := lq.ctx.Fields
	if len(columns) == 0 {
		columns = lik.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if lq.sql != nil {
		selector = lq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if lq.ctx.Unique != nil && *lq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range lq.predicates {
		p(selector)
	}
	for _, p := range lq.order {
		p(selector)
	}
	if offset := lq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := lq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LikGroupBy is the group-by builder for Lik entities.
type LikGroupBy struct {
	selector
	build *LikQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (lgb *LikGroupBy) Aggregate(fns ...AggregateFunc) *LikGroupBy {
	lgb.fns = append(lgb.fns, fns...)
	return lgb
}

// Scan applies the selector query and scans the result into the given value.
func (lgb *LikGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lgb.build.ctx, "GroupBy")
	if err := lgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LikQuery, *LikGroupBy](ctx, lgb.build, lgb, lgb.build.inters, v)
}

func (lgb *LikGroupBy) sqlScan(ctx context.Context, root *LikQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(lgb.fns))
	for _, fn := range lgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*lgb.flds)+len(lgb.fns))
		for _, f := range *lgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*lgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LikSelect is the builder for selecting fields of Lik entities.
type LikSelect struct {
	*LikQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ls *LikSelect) Aggregate(fns ...AggregateFunc) *LikSelect {
	ls.fns = append(ls.fns, fns...)
	return ls
}

// Scan applies the selector query and scans the result into the given value.
func (ls *LikSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ls.ctx, "Select")
	if err := ls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LikQuery, *LikSelect](ctx, ls.LikQuery, ls, ls.inters, v)
}

func (ls *LikSelect) sqlScan(ctx context.Context, root *LikQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ls.fns))
	for _, fn := range ls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
