// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/jeffreycharters/blurt/ent/blurt"
	"github.com/jeffreycharters/blurt/ent/lik"
	"github.com/jeffreycharters/blurt/ent/user"
)

// LikCreate is the builder for creating a Lik entity.
type LikCreate struct {
	config
	mutation *LikMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (lc *LikCreate) SetUserID(u uuid.UUID) *LikCreate {
	lc.mutation.SetUserID(u)
	return lc
}

// SetBlurtID sets the "blurt_id" field.
func (lc *LikCreate) SetBlurtID(u uuid.UUID) *LikCreate {
	lc.mutation.SetBlurtID(u)
	return lc
}

// SetUser sets the "user" edge to the User entity.
func (lc *LikCreate) SetUser(u *User) *LikCreate {
	return lc.SetUserID(u.ID)
}

// SetBlurt sets the "blurt" edge to the Blurt entity.
func (lc *LikCreate) SetBlurt(b *Blurt) *LikCreate {
	return lc.SetBlurtID(b.ID)
}

// Mutation returns the LikMutation object of the builder.
func (lc *LikCreate) Mutation() *LikMutation {
	return lc.mutation
}

// Save creates the Lik in the database.
func (lc *LikCreate) Save(ctx context.Context) (*Lik, error) {
	return withHooks(ctx, lc.sqlSave, lc.mutation, lc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (lc *LikCreate) SaveX(ctx context.Context) *Lik {
	v, err := lc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lc *LikCreate) Exec(ctx context.Context) error {
	_, err := lc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lc *LikCreate) ExecX(ctx context.Context) {
	if err := lc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lc *LikCreate) check() error {
	if _, ok := lc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Lik.user_id"`)}
	}
	if _, ok := lc.mutation.BlurtID(); !ok {
		return &ValidationError{Name: "blurt_id", err: errors.New(`ent: missing required field "Lik.blurt_id"`)}
	}
	if _, ok := lc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Lik.user"`)}
	}
	if _, ok := lc.mutation.BlurtID(); !ok {
		return &ValidationError{Name: "blurt", err: errors.New(`ent: missing required edge "Lik.blurt"`)}
	}
	return nil
}

func (lc *LikCreate) sqlSave(ctx context.Context) (*Lik, error) {
	if err := lc.check(); err != nil {
		return nil, err
	}
	_node, _spec := lc.createSpec()
	if err := sqlgraph.CreateNode(ctx, lc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}

func (lc *LikCreate) createSpec() (*Lik, *sqlgraph.CreateSpec) {
	var (
		_node = &Lik{config: lc.config}
		_spec = sqlgraph.NewCreateSpec(lik.Table, nil)
	)
	if nodes := lc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   lik.UserTable,
			Columns: []string{lik.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := lc.mutation.BlurtIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   lik.BlurtTable,
			Columns: []string{lik.BlurtColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(blurt.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.BlurtID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LikCreateBulk is the builder for creating many Lik entities in bulk.
type LikCreateBulk struct {
	config
	err      error
	builders []*LikCreate
}

// Save creates the Lik entities in the database.
func (lcb *LikCreateBulk) Save(ctx context.Context) ([]*Lik, error) {
	if lcb.err != nil {
		return nil, lcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(lcb.builders))
	nodes := make([]*Lik, len(lcb.builders))
	mutators := make([]Mutator, len(lcb.builders))
	for i := range lcb.builders {
		func(i int, root context.Context) {
			builder := lcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LikMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, lcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, lcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, lcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (lcb *LikCreateBulk) SaveX(ctx context.Context) []*Lik {
	v, err := lcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lcb *LikCreateBulk) Exec(ctx context.Context) error {
	_, err := lcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lcb *LikCreateBulk) ExecX(ctx context.Context) {
	if err := lcb.Exec(ctx); err != nil {
		panic(err)
	}
}
